spring.application.name=journalApp
#spring.data.mongodb.host=localhost
#spring.data.mogodb.port=27017
spring.data.mongodb.uri=mongodb+srv://myselfanonymous404_db_user:V74fEKP3Z5l3rcUL@cluster0.6z5bzej.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journalDB
spring.data.mongodb.auto-index-creation=true
 